"""Model-aware contracts and deterministic adapter registry for RIPPLe."""

from .adapters import (
    AdapterIdentity,
    CompatibilityIssue,
    CompatibilityResult,
    DeterministicPreprocessingAdapter,
    PreprocessingInvocation,
    PreprocessingRunEnvelope,
    VerifiedInputPackageRef,
)
from .agent_contracts import (
    AgentPhaseTrace,
    AgentRuntimeIdentity,
    AgentToolActivity,
    AgentUsageRecord,
    ModelOnboardingAgentOutcome,
    OnboardingAgentLimits,
    OnboardingSemanticProposal,
    SourceAnalysisProposal,
    assemble_model_contract_draft,
)
from .agent_io import (
    AgentArtifactIOError,
    load_agent_outcome,
    load_onboarding_request,
    load_source_inventory,
    write_agent_outcome,
    write_onboarding_request,
    write_source_inventory,
)
from .agent_provider import (
    LiveAgentConfiguration,
    LiveAgentConfigurationError,
    build_openai_responses_model_from_environment,
    load_live_agent_configuration,
)
from .contracts import (
    ComponentRequirements,
    EvidenceClaim,
    EvidenceSource,
    ImplementationIdentity,
    ModelManifest,
    ModelManifestRef,
    NumericRange,
    ObservationRequirements,
    OutputContract,
    PreprocessingContract,
    QualificationRecord,
    TensorContract,
    TransformStep,
)
from .manifest_io import (
    ModelManifestIOError,
    load_builtin_manifests,
    load_model_manifest,
    write_model_manifest_atomic,
)
from .observation import (
    ObservationBundle,
    ObservationBundleError,
    ObservationPlane,
    load_observation_bundle,
)
from .onboarding import (
    DeterministicQualificationReport,
    EvidenceLocation,
    HumanApprovalFreezeRequest,
    ModelContractDraft,
    ModelOnboardingRequest,
    QualificationFinding,
    RequirementConflict,
    RequirementFinding,
    SourceArtifact,
    SourceInventory,
)
from .qualification import qualify_model_contract_draft
from .research_agent import (
    OpenResearchAgentUnavailableError,
    build_open_research_planner,
    build_open_research_result_agent,
    run_open_research_agent,
    run_open_research_from_inventory,
)
from .research_contracts import (
    ALLOWLISTED_RESEARCH_ACTIONS,
    FinalResearchResult,
    OpenResearchOutcome,
    OpenResearchRequest,
    ResearchAgentLimits,
    ResearchEvidence,
    ResearchFinding,
    ResearchPlan,
    ResearchPlanStep,
    ResearchRunUsage,
    SuccessCriterionAssessment,
)
from .research_snapshot import (
    InventoriedRepositorySnapshot,
    SafeRepositorySnapshot,
)
from .registry import ModelAdapterRegistry, RegistryError
from .source_inventory import (
    LocalInventoryPolicy,
    inventory_local_sources,
    inventory_source_tree_sha256,
)
from .source_reader import SourceExcerpt, read_source_excerpt

__all__ = [
    "AdapterIdentity",
    "AgentArtifactIOError",
    "AgentPhaseTrace",
    "AgentRuntimeIdentity",
    "AgentToolActivity",
    "AgentUsageRecord",
    "CompatibilityIssue",
    "CompatibilityResult",
    "ComponentRequirements",
    "DeterministicPreprocessingAdapter",
    "DeterministicQualificationReport",
    "EvidenceClaim",
    "EvidenceSource",
    "EvidenceLocation",
    "HumanApprovalFreezeRequest",
    "ImplementationIdentity",
    "LiveAgentConfiguration",
    "LiveAgentConfigurationError",
    "ModelAdapterRegistry",
    "ModelContractDraft",
    "ModelManifest",
    "ModelManifestIOError",
    "ModelManifestRef",
    "ModelOnboardingAgentOutcome",
    "ModelOnboardingRequest",
    "NumericRange",
    "OnboardingAgentLimits",
    "OnboardingSemanticProposal",
    "ObservationBundle",
    "ObservationBundleError",
    "ObservationPlane",
    "ObservationRequirements",
    "OutputContract",
    "PreprocessingContract",
    "PreprocessingInvocation",
    "PreprocessingRunEnvelope",
    "QualificationFinding",
    "QualificationRecord",
    "RegistryError",
    "RequirementConflict",
    "RequirementFinding",
    "SourceArtifact",
    "SourceAnalysisProposal",
    "SourceExcerpt",
    "SourceInventory",
    "LocalInventoryPolicy",
    "ALLOWLISTED_RESEARCH_ACTIONS",
    "FinalResearchResult",
    "InventoriedRepositorySnapshot",
    "OpenResearchAgentUnavailableError",
    "OpenResearchOutcome",
    "OpenResearchRequest",
    "ResearchAgentLimits",
    "ResearchEvidence",
    "ResearchFinding",
    "ResearchPlan",
    "ResearchPlanStep",
    "ResearchRunUsage",
    "SuccessCriterionAssessment",
    "SafeRepositorySnapshot",
    "TensorContract",
    "TransformStep",
    "VerifiedInputPackageRef",
    "assemble_model_contract_draft",
    "build_openai_responses_model_from_environment",
    "inventory_local_sources",
    "inventory_source_tree_sha256",
    "load_agent_outcome",
    "load_builtin_manifests",
    "load_model_manifest",
    "load_onboarding_request",
    "load_source_inventory",
    "load_observation_bundle",
    "qualify_model_contract_draft",
    "read_source_excerpt",
    "build_open_research_planner",
    "build_open_research_result_agent",
    "run_open_research_agent",
    "run_open_research_from_inventory",
    "load_live_agent_configuration",
    "write_agent_outcome",
    "write_onboarding_request",
    "write_source_inventory",
    "write_model_manifest_atomic",
]
